version: '3'
services: 
  database:
    image: "postgres"
    env_file:
      - .db.local.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5409:5432"
volumes:
  database-data: